ax = gca; % current axes
ax.FontWeight='bold';
ax.FontSize = 15;
ax.FontName='times new roman';
ax.TickDir = 'both';
ax.FontWeight='bold';
ax.Box='off';
ax.XGrid='on';
ax.YGrid='on';
Legend.FontName='times new roman';
Legend.FontSize=15;
Legend.FontWeight='normal';
Legend.Box = 'on';
